# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: my@mail.com
author_name: John Doe
contract_name: tree_coin
deployment_language: python
preset_name: starter
project_name: tree_coin

